### ISSUE TITLE
No command line interface

### ISSUE THREAD

**Issue by borisindelman** [lsperling/PhishDetector#3]
Consider adding an option to invoke the detector with arguments
``` sh
python phish_detector.py --url='www.just-but-but-bur.more'
```

you can do it in a separate script or in the main of the phish_detector.py.

see python argparser for an easy implementation
https://stackoverflow.com/questions/7427101/simple-argparse-example-wanted-1-argument-3-results

**Comment by lsperling** [comment]
Done & updated 'how to use' section
